CREATE DATABASE demo;
USE demo;
CREATE TABLE CUSTOMERS(
ID INT NOT NULL,
NAME VARCHAR(20) NOT NULL,
AGE INT NOT NULL,
ADRESS CHAR(25),
SALARY DECIMAL(18,2),
PRIMARY KEY(ID)
);

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADRESS,SALARY)
VALUES(1,'Ramesh',32,'Ahmedabad',2000.00);

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADRESS,SALARY)
VALUES(2,'Khilan',25,'Delhi',1500.00);

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADRESS,SALARY)
VALUES(3,'Kaushik',23,'Kota',2000.00);

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADRESS,SALARY)
VALUES(4,'Chaitali',25,'Mumbai',6500.00);

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADRESS,SALARY)
VALUES(5,'Hardik',27,'Bhopal',8500.00);

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADRESS,SALARY)
VALUES(6,'Komal',22,'MP',4500.00);

INSERT INTO CUSTOMERS
VALUES(7,'Muffy',24,'Indore',10000.00);

SELECT * FROM CUSTOMERS;

SELECT ID,NAME,SALARY FROM CUSTOMERS WHERE SALARY>2000;
SELECT ID,NAME,SALARY FROM CUSTOMERS  WHERE SALARY>2000 AND AGE<25;
SELECT ID,NAME,SALARY FROM CUSTOMERS  WHERE SALARY>2000 OR AGE<25;
UPDATE CUSTOMERS SET ADRESS='Pune' WHERE ID = 6;
SELECT * FROM CUSTOMERS;
SELECT SALARY FROM CUSTOMERS ORDER BY SALARY;
SELECT MAX(SALARY) AS second_highest_salary FROM CUSTOMERS WHERE SALARY< (SELECT MAX(SALARY) FROM CUSTOMERS);